title: NLP/CL Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to deadlines for CompLings at SBULing
author: Salam Khalifa

domain: "https://slkh.github.io/NLP-CL-deadlines/"
baseurl: /NLP-CL-deadlines

twitter_username: salamkhalifa
twitter_hashtag: compling
github_username: slkh
github_repo: nlp-cl-deadlines

markdown: kramdown
#ga_id: UA-36274081-2

include: ['_pages']
